import { EnrolledService } from '../../../types';

export const mockEnrolledServices: EnrolledService[] = [
  {
    id: 'gst-001',
    name: 'Quarterly GST Filing',
    category: 'GST',
    status: 'Pending Action',
    progress: 75,
    consultant: { name: 'Priya Singh', avatar: 'https://i.pravatar.cc/150?u=priya' },
    startDate: '2024-07-01',
    nextActionDate: '2024-07-25',
    description: 'Filing of GSTR-1 and GSTR-3B for Q2. Awaiting sales ledger from client.',
  },
  {
    id: 'tax-001',
    name: 'Annual Tax Filing',
    category: 'Tax',
    status: 'Active',
    progress: 40,
    consultant: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
    startDate: '2024-06-15',
    description: 'Preparation and filing of annual income tax returns for FY 2023-24.',
  },
  {
    id: 'legal-001',
    name: 'Vendor Contract Review',
    category: 'Legal',
    status: 'Completed',
    progress: 100,
    consultant: { name: 'Sarah Smith', avatar: 'https://i.pravatar.cc/150?u=sarah' },
    startDate: '2024-05-20',
    description: 'Review and vetting of the new software vendor agreement.',
  },
    {
    id: 'startup-001',
    name: 'Company Incorporation',
    category: 'Startup',
    status: 'Completed',
    progress: 100,
    consultant: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
    startDate: '2024-04-10',
    description: 'Successfully incorporated "Acme Innovations Pvt. Ltd."',
  },
  {
    id: 'audit-001',
    name: 'Annual Financial Audit',
    category: 'Audit',
    status: 'Active',
    progress: 20,
    consultant: { name: 'Priya Singh', avatar: 'https://i.pravatar.cc/150?u=priya' },
    startDate: '2024-07-10',
    description: 'Conducting the statutory financial audit for the previous fiscal year.',
  },
    {
    id: 'tax-002',
    name: 'TDS Return Filing',
    category: 'Tax',
    status: 'On Hold',
    progress: 10,
    consultant: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
    startDate: '2024-07-05',
    description: 'Awaiting clarification on certain invoices before filing the TDS return.',
  },
];
