
import { Service, ServiceDocument } from '../../types';

export const mockServices: Service[] = [
  {
    id: 'gst-001',
    title: 'GST Registration',
    clientName: 'Acme Corporation',
    organization: 'Acme Corp',
    email: 'acme@company.com',
    phone: '+91 98765 43210',
    category: 'GST',
    status: 'In Progress',
    priority: 'Medium',
    description: 'GST registration for new business entity.',
    progress: 75,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [3],
    documents: 3,
    startDate: '2024-07-15',
  },
  {
    id: 'tax-001',
    title: 'Income Tax Filing',
    clientName: 'Tech Solutions Pvt Ltd',
    organization: 'Tech Solutions',
    email: 'info@techsolutions.com',
    phone: '+91 87654 32109',
    category: 'Tax',
    status: 'Completed',
    priority: 'High',
    description: 'Annual income tax filing and compliance.',
    progress: 100,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [8],
    documents: 5,
    startDate: '2024-06-20',
  },
  {
    id: 'startup-001',
    title: 'Company Registration',
    clientName: 'Green Energy Startup',
    organization: 'Green Energy',
    email: 'contact@greenenergy.com',
    phone: '+91 76543 21098',
    category: 'Startup',
    status: 'New',
    priority: 'Low',
    description: 'Private limited company registration.',
    progress: 10,
    assignedTeam: 'Unassigned',
    assignedEmployeeIds: [],
    documents: 1,
    startDate: '2024-07-18',
  },
  {
    id: 'legal-001',
    title: 'Contract Review',
    clientName: 'Innovate LLC',
    organization: 'Innovate LLC',
    email: 'legal@innovate.com',
    phone: '+91 91234 56789',
    category: 'Legal',
    status: 'In Progress',
    priority: 'High',
    description: 'Review of vendor contracts for the new software procurement.',
    progress: 50,
    assignedTeam: 'Legal Team',
    assignedEmployeeIds: [],
    documents: 2,
    startDate: '2024-07-10',
  },
  {
    id: 'audit-001',
    title: 'Security Audit',
    clientName: 'SecureNet Inc.',
    organization: 'SecureNet',
    email: 'security@securenet.com',
    phone: '+91 89876 54321',
    category: 'Audit',
    status: 'New',
    priority: 'Medium',
    description: 'Annual security audit and penetration testing.',
    progress: 0,
    assignedTeam: 'IT Team',
    assignedEmployeeIds: [7],
    documents: 0,
    startDate: '2024-07-20',
  },
    {
    id: 'gst-002',
    title: 'Quarterly GST Filing',
    clientName: 'Retail Goods Co.',
    organization: 'Retail Goods',
    email: 'accounts@retailgoods.com',
    phone: '+91 78901 23456',
    category: 'GST',
    status: 'On Hold',
    priority: 'Medium',
    description: 'Filing of GSTR-1 and GSTR-3B for Q2.',
    progress: 25,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [3, 8],
    documents: 4,
    startDate: '2024-07-01',
  }
];

export const mockServiceDocuments: Record<string, ServiceDocument[]> = {
  'gst-001': [
    { id: 'sdoc1-1', name: 'GST_Application.pdf', type: 'Client Brief', url: '#', size: '300 KB', uploadDate: '2024-07-15' },
    { id: 'sdoc1-2', name: 'PAN_Card.pdf', type: 'Client Brief', url: '#', size: '1.1 MB', uploadDate: '2024-07-15' },
    { id: 'sdoc1-3', name: 'Address_Proof.pdf', type: 'Client Brief', url: '#', size: '900 KB', uploadDate: '2024-07-16' },
  ],
  'tax-001': [
    { id: 'sdoc2-1', name: 'Form_16.pdf', type: 'Client Brief', url: '#', size: '450 KB', uploadDate: '2024-06-20' },
    { id: 'sdoc2-2', name: 'Bank_Statement_Mar.pdf', type: 'Client Brief', url: '#', size: '2.5 MB', uploadDate: '2024-06-21' },
    { id: 'sdoc2-3', name: 'Investment_Proofs.zip', type: 'Client Brief', url: '#', size: '5.2 MB', uploadDate: '2024-06-22' },
    { id: 'sdoc2-4', name: 'Tax_Computation.xlsx', type: 'Report', url: '#', size: '150 KB', uploadDate: '2024-07-10' },
    { id: 'sdoc2-5', name: 'Acknowledgement.pdf', type: 'Report', url: '#', size: '120 KB', uploadDate: '2024-07-12' },
  ],
  'startup-001': [
    { id: 'sdoc3-1', name: 'Director_KYC.zip', type: 'Client Brief', url: '#', size: '3.1 MB', uploadDate: '2024-07-18' },
  ],
  'legal-001': [
    { id: 'sdoc4-1', name: 'Vendor_Agreement_Draft.docx', type: 'Contract', url: '#', size: '88 KB', uploadDate: '2024-07-10' },
    { id: 'sdoc4-2', name: 'Procurement_Policy.pdf', type: 'Client Brief', url: '#', size: '400 KB', uploadDate: '2024-07-11' },
  ],
  'gst-002': [
    { id: 'sdoc5-1', name: 'Sales_Ledger_Q2.csv', type: 'Client Brief', url: '#', size: '1.8 MB', uploadDate: '2024-07-01' },
    { id: 'sdoc5-2', name: 'Purchase_Ledger_Q2.csv', type: 'Client Brief', url: '#', size: '950 KB', uploadDate: '2024-07-01' },
    { id: 'sdoc5-3', name: 'Expense_Invoices.zip', type: 'Invoice', url: '#', size: '10.5 MB', uploadDate: '2024-07-02' },
    { id: 'sdoc5-4', name: 'Previous_GSTR1.pdf', type: 'Report', url: '#', size: '220 KB', uploadDate: '2024-07-03' },
  ],
};