
import { Project, Employee } from '../../types';

// FIX: Added missing properties to each employee object to match the `Employee` type definition.
export const mockEmployees: Employee[] = [
  { 
    id: 1, 
    name: 'Jayesh Patel', 
    position: 'Lead Developer', 
    department: 'IT', 
    avatar: 'https://picsum.photos/seed/1/40/40', 
    performanceScore: 95,
    email: 'jayesh.patel@corporatesaathi.com',
    phone: '+91 98765 43210',
    joiningDate: '2018-05-20',
    dob: '1990-02-15',
    address: '123 Tech Park, Bangalore, India',
    status: 'Active',
  },
  { 
    id: 2, 
    name: 'Sarah Smith', 
    position: 'Frontend Developer', 
    department: 'IT', 
    avatar: 'https://picsum.photos/seed/2/40/40', 
    performanceScore: 92,
    email: 'sarah.smith@corporatesaathi.com',
    phone: '+91 91234 56789',
    joiningDate: '2020-09-01',
    dob: '1995-11-12',
    address: '456 Web Street, Mumbai, India',
    status: 'Active',
  },
  { 
    id: 3, 
    name: 'John Doe', 
    position: 'Accountant', 
    department: 'Finance', 
    avatar: 'https://picsum.photos/seed/3/40/40', 
    performanceScore: 88,
    email: 'john.doe@corporatesaathi.com',
    phone: '+91 87654 32109',
    joiningDate: '2019-03-10',
    dob: '1992-07-25',
    address: '789 Finance Ave, Delhi, India',
    status: 'On Leave',
  },
  { 
    id: 4, 
    name: 'Anna Rodriguez', 
    position: 'HR Manager', 
    department: 'HR', 
    avatar: 'https://picsum.photos/seed/4/40/40', 
    performanceScore: 94,
    email: 'anna.rodriguez@corporatesaathi.com',
    phone: '+91 76543 21098',
    joiningDate: '2017-11-22',
    dob: '1988-12-30',
    address: '101 People Plaza, Pune, India',
    status: 'Active',
  },
  { 
    id: 5, 
    name: 'Mike Harper', 
    position: 'Backend Developer', 
    department: 'IT', 
    avatar: 'https://picsum.photos/seed/5/40/40', 
    performanceScore: 85,
    email: 'mike.harper@corporatesaathi.com',
    phone: '+91 65432 10987',
    joiningDate: '2021-02-15',
    dob: '1996-04-05',
    address: '212 Server Side, Hyderabad, India',
    status: 'Active',
  },
  { 
    id: 6, 
    name: 'Chris Smith', 
    position: 'Recruiter', 
    department: 'HR', 
    avatar: 'https://picsum.photos/seed/6/40/40', 
    performanceScore: 89,
    email: 'chris.smith@corporatesaathi.com',
    phone: '+91 89876 54321',
    joiningDate: '2022-01-05',
    dob: '1994-08-19',
    address: '321 Talent Trail, Chennai, India',
    status: 'Terminated',
  },
  { 
    id: 7, 
    name: 'Priya Singh', 
    position: 'DevOps Engineer', 
    department: 'IT', 
    avatar: 'https://picsum.photos/seed/7/40/40', 
    performanceScore: 98,
    email: 'priya.singh@corporatesaathi.com',
    phone: '+91 78901 23456',
    joiningDate: '2019-08-12',
    dob: '1993-01-22',
    address: '432 Pipeline Path, Bangalore, India',
    status: 'Active',
  },
  { 
    id: 8, 
    name: 'Tom Baker', 
    position: 'Financial Analyst', 
    department: 'Finance', 
    avatar: 'https://picsum.photos/seed/8/40/40', 
    performanceScore: 91,
    email: 'tom.baker@corporatesaathi.com',
    phone: '+91 90123 45678',
    joiningDate: '2020-06-25',
    dob: '1991-06-18',
    address: '543 Market St, Kolkata, India',
    status: 'Active',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Corporate Website Redesign',
    department: 'IT',
    subDepartment: 'Web Development',
    status: 'Active',
    priority: 'High',
    progress: 75,
    description: 'Complete overhaul of the main corporate website with a new CMS.',
    startDate: '2024-05-01',
    endDate: '2024-08-30',
    assignedEmployees: [1, 2, 5],
  },
  {
    id: 'proj-2',
    name: 'Q3 Financial Audit',
    department: 'Finance',
    status: 'Active',
    priority: 'High',
    progress: 40,
    description: 'Internal audit of all financial records for the third quarter.',
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    assignedEmployees: [3, 8],
  },
  {
    id: 'proj-3',
    name: 'New Employee Onboarding Platform',
    department: 'HR',
    status: 'Pending',
    priority: 'Medium',
    progress: 10,
    description: 'Develop a new digital platform for onboarding new hires.',
    startDate: '2024-08-01',
    endDate: '2024-11-15',
    assignedEmployees: [4, 6],
  },
  {
    id: 'proj-4',
    name: 'Mobile App for Clients',
    department: 'IT',
    subDepartment: 'App Development',
    status: 'Completed',
    priority: 'High',
    progress: 100,
    description: 'Launched the new client-facing mobile application for iOS and Android.',
    startDate: '2024-01-10',
    endDate: '2024-06-20',
    assignedEmployees: [1, 2, 7],
  },
    {
    id: 'proj-5',
    name: 'Cloud Infrastructure Migration',
    department: 'IT',
    subDepartment: 'Server Development',
    status: 'Active',
    priority: 'Medium',
    progress: 60,
    description: 'Migrate all on-premise servers to a cloud-based solution.',
    startDate: '2024-04-15',
    endDate: '2024-09-01',
    assignedEmployees: [5, 7],
  },
  {
    id: 'proj-6',
    name: '2025 Budget Planning',
    department: 'Finance',
    status: 'Pending',
    priority: 'Medium',
    progress: 0,
    description: 'Initial planning and forecasting for the 2025 fiscal year budget.',
    startDate: '2024-09-01',
    endDate: '2024-10-31',
    assignedEmployees: [3, 8],
  },
    {
    id: 'proj-7',
    name: 'Performance Review System Update',
    department: 'HR',
    status: 'Completed',
    priority: 'Low',
    progress: 100,
    description: 'Updated the quarterly performance review templates and workflow.',
    startDate: '2024-05-20',
    endDate: '2024-06-15',
    assignedEmployees: [4],
  },
];
