import { ClientDocument } from '../../../types';

export const mockDocuments: ClientDocument[] = [
  {
    id: 'doc-01',
    name: 'Sales Ledger Q2.csv',
    serviceId: 'gst-001',
    serviceName: 'Quarterly GST Filing',
    type: 'Uploaded by You',
    uploadDate: '2024-07-18',
    size: '1.2 MB',
    url: '#',
  },
  {
    id: 'doc-02',
    name: 'Draft Tax Computation.pdf',
    serviceId: 'tax-001',
    serviceName: 'Annual Tax Filing',
    type: 'Provided by Us',
    uploadDate: '2024-07-15',
    size: '450 KB',
    url: '#',
  },
  {
    id: 'doc-03',
    name: 'Vendor Agreement Final.pdf',
    serviceId: 'legal-001',
    serviceName: 'Vendor Contract Review',
    type: 'Provided by Us',
    uploadDate: '2024-06-25',
    size: '800 KB',
    url: '#',
  },
  {
    id: 'doc-04',
    name: 'Investment Proofs.zip',
    serviceId: 'tax-001',
    serviceName: 'Annual Tax Filing',
    type: 'Uploaded by You',
    uploadDate: '2024-06-20',
    size: '5.6 MB',
    url: '#',
  },
   {
    id: 'doc-05',
    name: 'Certificate of Incorporation.pdf',
    serviceId: 'startup-001',
    serviceName: 'Company Incorporation',
    type: 'Provided by Us',
    uploadDate: '2024-05-30',
    size: '1.1 MB',
    url: '#',
  },
];
